version: "3"

services:
  db:
    image: postgres:16.2-alpine
    container_name: student-accommodation-local-db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: localadmin
      POSTGRES_DB: studentaccommodationlocaldb
    ports:
      - "5432:5432"

  student-accommodation-back-end:
    container_name: student-accommodation-back-end
    image: student-accommodation-back-end:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    environment:
      - POSTGRES_DB=studentaccommodationlocaldb
      - USER_DB=localadmin
      - PASSWORD_DB=admin
      - DB_URL=jdbc:postgresql://db:5432/studentaccommodationlocaldb
      - JWT_SECRET=jvc+QC/0myyJ9+//Rzo+qYxfMmHDiQdlysvcT9XhUF7/6mvHD9evZBB/ngNAMwTD6sDDQgf4vS0QDZ8JYLoBOA==
      - JWT_EXPIRATION=360000
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=student-accommodation-bucket

  minio:
    image: minio/minio
    container_name: student-accommodation-minio
    ports:
      - "9000:9000"  
      - "9001:9001"  
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  sonarqube-db:
    image: postgres:16.2-alpine
    container_name: student-accommodation-sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: student-accommodation-sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9002:9000"

  student-accommodation-front-end:
    container_name: student-accommodation-front-end
    build:
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "4200:80"
    depends_on:
      - student-accommodation-back-end
    environment:
      - API_URL=http://student-accommodation-back-end:8080
    volumes:
      - ./frontend/dist:/app/dist

volumes:
  minio_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_postgresql_data: